import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

/**
 * Local deployment script for the Hardhat network (chainId 31337).
 *
 * This script is designed for rapid local development:
 *   - Uses Hardhat's built-in mock USDC (MockERC20)
 *   - Sets the AI Director wallet as the paymaster so direct EOA
 *     transactions from the local AI Director can call mintFree()
 *   - Writes contract addresses to ../../.env.contracts for easy sourcing
 *
 * Run:
 *   npx hardhat node
 *   npx hardhat run scripts/deploy-local.ts --network localhost
 */

async function main(): Promise<void> {
  const [deployer, aiDirectorWallet] = await ethers.getSigners();
  console.log(`\nDeploying contracts with account: ${deployer.address}`);
  console.log(`AI Director wallet (local): ${aiDirectorWallet.address}`);
  console.log(`Balance: ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH\n`);

  // ── 1. Mock USDC ───────────────────────────────────────────────────────
  console.log("Deploying MockERC20 (USDC)...");
  const MockERC20 = await ethers.getContractFactory("MockERC20");
  const usdc = await MockERC20.deploy("Mock USDC", "mUSDC", 6);
  await usdc.waitForDeployment();
  const usdcAddress = await usdc.getAddress();
  console.log(`  MockUSDC deployed to: ${usdcAddress}`);

  // ── 2. CharacterSplitsFactory ──────────────────────────────────────────
  console.log("\nDeploying CharacterSplitsFactory...");
  const SplitsFactory = await ethers.getContractFactory("CharacterSplitsFactory");
  const splitsFactory = await SplitsFactory.deploy();
  await splitsFactory.waitForDeployment();
  const splitsFactoryAddress = await splitsFactory.getAddress();
  console.log(`  CharacterSplitsFactory deployed to: ${splitsFactoryAddress}`);

  // ── 3. CharacterNFT (with AI Director as temporary paymaster) ──────────
  console.log("\nDeploying CharacterNFT...");
  const CharacterNFT = await ethers.getContractFactory("CharacterNFT");
  const characterNFT = await CharacterNFT.deploy(
    usdcAddress,
    deployer.address,           // temporary recipient
    aiDirectorWallet.address,   // AI Director IS the paymaster for local dev
  );
  await characterNFT.waitForDeployment();
  const nftAddress = await characterNFT.getAddress();
  console.log(`  CharacterNFT deployed to: ${nftAddress}`);

  // ── 4. AIDirectorPaymaster ─────────────────────────────────────────────
  console.log("\nDeploying AIDirectorPaymaster...");
  const Paymaster = await ethers.getContractFactory("AIDirectorPaymaster");
  const paymaster = await Paymaster.deploy(nftAddress);
  await paymaster.waitForDeployment();
  const paymasterAddress = await paymaster.getAddress();
  console.log(`  AIDirectorPaymaster deployed to: ${paymasterAddress}`);

  // ── 5. Deploy default royalty split ────────────────────────────────────
  console.log("\nDeploying default CharacterSplits via factory...");
  const createSplitTx = await splitsFactory.createSplit(
    [deployer.address, aiDirectorWallet.address],
    [790_000, 200_000],
  );
  const receipt = await createSplitTx.wait();

  const splitDeployedEvent = receipt?.logs
    .map(log => {
      try { return splitsFactory.interface.parseLog(log); } catch { return null; }
    })
    .find(e => e?.name === "SplitDeployed");

  const splitAddress = splitDeployedEvent?.args[0] as string ?? "unknown";
  console.log(`  CharacterSplits deployed to: ${splitAddress}`);

  // ── 6. Update CharacterNFT payment recipient ───────────────────────────
  console.log("\nUpdating CharacterNFT payment recipient to splits contract...");
  const setRecipientTx = await characterNFT.setPaymentRecipient(splitAddress);
  await setRecipientTx.wait();
  console.log(`  Payment recipient updated to: ${splitAddress}`);

  // ── Summary ────────────────────────────────────────────────────────────
  const envLines = [
    "# Auto-generated by contracts/scripts/deploy-local.ts",
    `CHARACTER_NFT_ADDRESS=${nftAddress}`,
    `PAYMASTER_ADDRESS=${aiDirectorWallet.address}`,
    `SPLITS_FACTORY_ADDRESS=${splitsFactoryAddress}`,
    `DEFAULT_SPLIT_ADDRESS=${splitAddress}`,
    `USDC_ADDRESS=${usdcAddress}`,
    "BASE_RPC_URL=http://localhost:8545",
    "BUNDLER_URL=http://localhost:8545",
  ];

  const envPath = path.resolve(__dirname, "../../.env.contracts");
  fs.writeFileSync(envPath, envLines.join("\n") + "\n");

  console.log("\n" + "=".repeat(60));
  console.log("Local deployment complete!");
  console.log("=".repeat(60));
  console.log(envLines.join("\n"));
  console.log("=".repeat(60));
  console.log(`\nAddresses written to: ${envPath}`);
  console.log("Source them with:  export $(cat .env.contracts | xargs)\n");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
